FROM apache/spark-py:latest

USER root

# Download Spark Kafka connector and its dependencies (Spark 3.4.0 / Scala 2.12)
RUN curl -fSL -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.4.0.jar \
        https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.4.0/spark-sql-kafka-0-10_2.12-3.4.0.jar && \
    curl -fSL -o /opt/spark/jars/kafka-clients-3.4.0.jar \
        https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.0/kafka-clients-3.4.0.jar && \
    curl -fSL -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.4.0.jar \
        https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.4.0/spark-token-provider-kafka-0-10_2.12-3.4.0.jar && \
    curl -fSL -o /opt/spark/jars/commons-pool2-2.11.1.jar \
        https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

# Download PostgreSQL JDBC driver
RUN curl -fSL -o /opt/spark/jars/postgresql-42.7.1.jar \
        https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.1/postgresql-42.7.1.jar

USER 185
